name:                alarmclock
version:             0.7.0.6
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2014-2019 David Turner"
homepage:            https://github.com/DaveCTurner/alarmclock
category:            Concurrency

synopsis:            Wake up and perform an action at a certain time.

description:         Please see the README at <https://github.com/DaveCTurner/alarmclock/blob/master/README.md>

tested-with:         GHC ==8.10.7 || ==9.4.8 || ==9.8.2 || ==9.10.1

dependencies:
- base             >= 4.8.0 && < 5
- async            >= 2.1.1 && < 2.3
- stm              >= 2.4.4 && < 2.6
- clock            >= 0.7.0 && < 0.9
- time             >= 1.5.0 && < 1.15
- unbounded-delays >= 0.1.1 && < 0.2

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  alarmclock-test:
    main: Spec.hs
    source-dirs: test
    build-tools: hspec-discover:hspec-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alarmclock
    - hspec
