name:                alarmclock
version:             0.7.0.2
license:             BSD3
author:              "David Turner"
maintainer:          "dave.c.turner@gmail.com"
copyright:           "2014-2019 David Turner"
homepage:            https://github.com/DaveCTurner/alarmclock
category:            Concurrency

synopsis:            Wake up and perform an action at a certain time.

description:         Please see the README at <https://github.com/DaveCTurner/alarmclock/blob/master/README.md>

dependencies:
- base >=4.8 && <4.13
- stm
- async
- time
- clock
- unbounded-delays

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  alarmclock-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alarmclock
    - hspec
